kind: pipeline
type: docker
name: linux-arm

platform:
  os: linux
  arch: arm 

steps:
- name: docker internal 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.402.at/satis-go-docker
    registry: https://registry.402.at
    auto_tag_suffix: linux-arm
    auto_tag: true
    dockerfile: Dockerfile.arm
- name: dockerhub 
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: registry.hub.docker.com/nedaya/satis-go-docker
    registry: registry.hub.docker.com
    auto_tag_suffix: linux-arm
    auto_tag: true
    squash: true
    dockerfile: Dockerfile.arm

---    
kind: pipeline
type: docker
name: linux-arm64

platform:
    arch: arm64 
steps:      
- name: docker internal 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.402.at/satis-go-docker
    registry: https://registry.402.at
    auto_tag_suffix: linux-arm64
    auto_tag: true
    dockerfile: Dockerfile.arm64
- name: dockerhub 
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: registry.hub.docker.com/nedaya/satis-go-docker
    registry: registry.hub.docker.com
    auto_tag_suffix: linux-arm64
    auto_tag: true
    squash: true
    dockerfile: Dockerfile.arm64
---    
kind: pipeline
type: docker
name: linux-amd64

platform:
    arch: amd64 
steps:      
- name: docker internal 
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.402.at/satis-go-docker
    registry: https://registry.402.at
    auto_tag_suffix: linux-amd64
    auto_tag: true
- name: dockerhub 
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: registry.hub.docker.com/nedaya/satis-go-docker
    registry: registry.hub.docker.com
    auto_tag_suffix: linux-amd64
    auto_tag: true
    squash: true
    
    
---
kind: pipeline
type: docker
name: manifest

platform:
  arch: arm64 

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    auto_tag: true
    ignore_missing: true
    spec: docker/manifest.tmpl
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password

trigger:
  event:
  - push
  - tag

depends_on:
- linux-amd64
- linux-arm64
- linux-arm